name: Build

on:
  push:
    branches:
      - main
      - master
      - 'claude/**'
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Fetch Build Keyboards
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yaml2json
        run: python3 -m pip install remarshal

      - id: matrix
        name: Fetch Build Matrix
        run: |
          echo "matrix=$(yaml2json build.yaml | jq -c .)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    needs: matrix
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      # - name: West Update
      #   run: west update --narrow --fetch-opt=--depth=1

      # - name: West Zephyr export
      #   run: west zephyr-export

      - name: West Build (${{ matrix.board }}${{ matrix.shield && format(' - {0}', matrix.shield) || '' }})
        shell: sh -x {0}
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" ${{ matrix.shield && format('-DSHIELD={0}', matrix.shield) || '' }} ${{ matrix.cmake-args }}

      - name: ${{ matrix.shield }} ${{ matrix.board }} Kconfig file
        run: |
          if [ -f build/zephyr/.config ]
          then
            grep -v -e "^#" -e "^$" build/zephyr/.config | sort
          else
            echo "No Kconfig output"
          fi

      - name: Rename artifacts
        shell: sh -x {0}
        run: |
          mkdir build/artifacts
          if [ -f build/zephyr/zmk.uf2 ]
          then
            cp build/zephyr/zmk.uf2 "build/artifacts/${{ matrix.shield }}-${{ matrix.board }}-zmk.uf2"
          elif [ -f build/zephyr/zmk.hex ]
          then
            cp build/zephyr/zmk.hex "build/artifacts/${{ matrix.shield }}-${{ matrix.board }}-zmk.hex"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: build/artifacts
